CREATE TABLE admin(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(30) NOT NULL,
  password CHAR(60) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UNQ_email UNIQUE (email)
);
CREATE TABLE user(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(30) NOT NULL,
  password CHAR(60) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UNQ_email UNIQUE (email)
);
CREATE TABLE organizer(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(300) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  adminId INT UNSIGNED,
  FOREIGN KEY (adminId) REFERENCES admin(id) ON UPDATE CASCADE ON DELETE
  SET NULL
);
CREATE TABLE event(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(300) NOT NULL,
  organizerId INT UNSIGNED NOT NULL,
  address VARCHAR(300) NOT NULL,
  date TIMESTAMP NOT NULL,
  contactEmail VARCHAR(30),
  contactPhone VARCHAR(15),
  availableTickets INT UNSIGNED NOT NULL,
  price FLOAT(6, 2) UNSIGNED NOT NULL,
  adminId INT UNSIGNED,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CHK_contact CHECK (
    (contactEmail IS NOT NULL)
    OR (contactPhone IS NOT NULL)
  ),
  FOREIGN KEY (organizerId) REFERENCES organizer(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (adminId) REFERENCES admin(id) ON UPDATE CASCADE ON DELETE
  SET NULL
);
CREATE TABLE discount(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(10) NOT NULL,
  value TINYINT UNSIGNED NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eventId INT UNSIGNED,
  adminId INT UNSIGNED,
  CONSTRAINT CHK_value CHECK (value <= 100),
  CONSTRAINT UNQ_code UNIQUE (code),
  FOREIGN KEY (eventId) REFERENCES event(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (adminId) REFERENCES admin(id) ON UPDATE CASCADE ON DELETE
  SET NULL
);
CREATE TABLE ticket(
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  boughtAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eventId INT UNSIGNED,
  userId INT UNSIGNED,
  discountId INT UNSIGNED,
  FOREIGN KEY (eventId) REFERENCES event(id) ON UPDATE CASCADE ON DELETE
  SET NULL,
    FOREIGN KEY (userId) REFERENCES user(id) ON UPDATE CASCADE ON DELETE
  SET NULL,
    FOREIGN KEY (discountId) REFERENCES discount(id) ON UPDATE CASCADE ON DELETE
  SET NULL
);
CREATE TABLE cart(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  quantity INT UNSIGNED,
  eventId INT UNSIGNED,
  userId INT UNSIGNED,
  discountId INT UNSIGNED,
  FOREIGN KEY (eventId) REFERENCES event(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (discountId) REFERENCES discount(id) ON UPDATE CASCADE ON DELETE
  SET NULL
);