version: '3.9'
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'MBLABS'
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mb-labs-challenge

  api:
    image: challenge-api
    container_name: api
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - mb-labs-challenge

networks:
  mb-labs-challenge:
