version: '3.9'
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_TITLE
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/setup:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - mb-labs-challenge

  payment-webhooks:
    image: stripe/stripe-cli
    container_name: stripe-payments
    command: listen --forward-to $STRIPE_PAYMENT_WEBHOOK_URL --api-key $STRIPE_SECRET_KEY
    restart: unless-stopped
    networks:
      - mb-labs-challenge

  api:
    image: challenge-api
    container_name: api
    build: .
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - mb-labs-challenge

networks:
  mb-labs-challenge:
